{
    "name": "Real State",
    "version": "17.0.1.0.0",
    "category": "Extra Tools",
    "summary": "Real State Application",
    "sequence": "1",
    "author": "Samy Mostafa Shaawat",
    "maintainer": "Samy Mostafa Shaawat",
    "website": "https://samy.rowad.com/",
    "depends": [
        "base",
        "website",
        "mail",
        "sale_management",
        "stock",
        "contacts",
        "web_enterprise",
        "account",
        "account_accountant",
        "crm",
        "purchase",
        "website_sale",
        "appointment",
        "project_todo",
        "project",
        "calendar",
    ],
    "demo": [],
    "data": ["security/ir.model.access.csv", "data/sequence.xml"],
    "installable": True,
    "application": True,
}
