{
    'name': 'AI_assistant server',
    'summary': 'Diwan For Scientific Solution',
    'author': 'Powered By Diwan For Scientific Solution',
    'sequence': '0',
    'category': 'Extra Tools',
    'description': "Powered By Reap Holding - Smart Scientific Solutions",
    'depends': ['base', 'mail','agial_17'],
    'data': [
        'security/ir.model.access.csv',
        'views/agent.xml',
        'views/appointment.xml',
        'views/clinic.xml',
        'views/whatsapp.xml',
        "views/message_script.xml",
        "views/send_message_wizard.xml",
        'views/menus.xml',
    ],
    'version': '0.0.1',
    'application': True,
    'installable': True,
}
